FROM centos:6

RUN yum -y update \
    && yum install -y centos-release-scl \
    && yum install -y \
        git \
        rpm-build \
        make \
        glib2-devel \
        devtoolset-8-gcc \
        devtoolset-8-gcc-c++ \
        devtoolset-8-libatomic-devel \
    && yum clean all
